lib/meal_time_web/router.ex
defmodule MealTimeWeb.Router do
  use MealTimeWeb, :router

  pipeline :auth do
    plug MealTime.Auth.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MealTimeWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout
    get "/signup", UserController, :new
    post "/signup", UserController, :create
  end

  scope "/", MealTimeWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    resources "/meals", MealController,
      only: [:index, :new, :update, :edit, :create, :show, :delete]

    get "/secret", PageController, :secret
  end

  # Other scopes may use custom stacks.
  # scope "/api", MealTimeWeb do
  #   pipe_through :api
  # end
end

lib/meal_time_web/views/layout_view.ex
defmodule MealTimeWeb.LayoutView do
  use MealTimeWeb, :view

  def show_alert(conn) do
    conn
    |> get_flash
    |> flash_message
  end

  def flash_message(%{"info" => message}) do
    render MealTimeWeb.SharedView, "_alert.html", class: "uk-alert-primary", message: message
  end

  def flash_message(%{"error" => message}) do
    render MealTimeWeb.SharedView, "_alert.html", class: "uk-alert-danger", message: message
  end

  def flash_message(_), do: nil
end

lib/meal_time_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>MealTime · Phoenix Framework</title>
    <!-- UIkit CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/css/uikit.min.css" />

<!-- UIkit JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/js/uikit-icons.min.js"></script>


    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header class="uk-margin">
      <nav class="uk-navbar-container" uk-navbar>
        <div class="uk-navbar-left">
          <ul class="uk-navbar-nav">
            <li class="uk-active"><%= link "MealTime", to: Routes.meal_path(@conn, :index) %></li>
          </ul>
        </div>
        <div class="uk-navbar-right">
          <ul class="uk-navbar-nav">
            <%= if @current_user do %>
              <li><%= link "Welcome, #{@current_user.email}", to: Routes.session_path(@conn, :logout) %></li>
            <% else %>
              <li><%= link "Log In", to: Routes.session_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <main role="main" class="uk-container">
      <%= show_alert(@conn) %>

      <div>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>